### ISSUE TITLE
Remove `Next` and unnecessary dependencies

### ISSUE THREAD

**Issue by felix-gehring** [SODEFA-GmbH-Co-KG/zwilling#1]
Mach mal ne schlanke Lib raus und dann ab zu NPM. :rocket: Würd ich sofort nutzen!
@rechenberger

**Comment by rechenberger** [comment]
Done! 
- `next` (and all other dependencies) are moved to devDependencies
- dropping `next` for the demo is planned: #9 
- Library published: https://www.npmjs.com/package/zwilling
